# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Se2ROuqvCgSnAOwPcwcpdWYHHWAma4t
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
import plotly.express as px
import plotly.graph_objects as go

# Configuración de la página
st.set_page_config(page_title="Clasificación Iris", page_icon="🌿", layout="wide")

# Cargar datos desde sklearn
@st.cache_data
def load_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['species'] = iris.target
    df['species_name'] = df['species'].map({0: 'Iris-setosa', 1: 'Iris-versicolor', 2: 'Iris-virginica'})
    return df

df = load_data()

# Renombrar columnas
df = df.rename(columns={
    'sepal length (cm)': 'SepalLengthCm',
    'sepal width (cm)': 'SepalWidthCm',
    'petal length (cm)': 'PetalLengthCm',
    'petal width (cm)': 'PetalWidthCm'
})

features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
species_names = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

# Entrenar modelo
X = df[features]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Streamlit Dashboard
st.title("🌿 Clasificación de Especies de Iris")
st.write("Dashboard interactivo para predecir la especie de una flor Iris basada en sus medidas.")

# Sidebar para navegación
st.sidebar.title("Navegación")
section = st.sidebar.radio("Ir a:", ["📊 Métricas", "🔮 Predecir", "📈 Datos"])

if section == "📊 Métricas":
    st.header("📊 Métricas del Modelo")

    # Métricas principales
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Exactitud", f"{accuracy_score(y_test, y_pred):.2f}")
    with col2:
        st.metric("Precisión", f"{precision_score(y_test, y_pred, average='weighted'):.2f}")
    with col3:
        st.metric("Sensibilidad", f"{recall_score(y_test, y_pred, average='weighted'):.2f}")
    with col4:
        st.metric("F1-Score", f"{f1_score(y_test, y_pred, average='weighted'):.2f}")

    # Matriz de confusión
    st.subheader("Matriz de Confusión")
    cm = confusion_matrix(y_test, y_pred)
    fig_cm = px.imshow(cm,
                       labels=dict(x="Predicho", y="Real", color="Cantidad"),
                       x=species_names,
                       y=species_names)
    st.plotly_chart(fig_cm)

elif section == "🔮 Predecir":
    st.header("🔮 Predecir Especie")

    # Entrada de usuario
    col1, col2 = st.columns(2)

    with col1:
        sepal_length = st.slider("Longitud Sépalo (cm)", 4.0, 8.0, 5.8)
        sepal_width = st.slider("Ancho Sépalo (cm)", 2.0, 4.5, 3.0)

    with col2:
        petal_length = st.slider("Longitud Pétalo (cm)", 1.0, 7.0, 4.0)
        petal_width = st.slider("Ancho Pétalo (cm)", 0.1, 2.5, 1.2)

    if st.button("Predecir Especie"):
        input_data = scaler.transform([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(input_data)[0]
        prediction_proba = model.predict_proba(input_data)[0]
        species_name = species_names[prediction]

        st.success(f"**Especie Predicha: {species_name}**")

        # Probabilidades
        prob_df = pd.DataFrame({
            'Especie': species_names,
            'Probabilidad': prediction_proba
        })
        fig_proba = px.bar(prob_df, x='Especie', y='Probabilidad',
                          title="Probabilidades de Predicción")
        st.plotly_chart(fig_proba)

else:  # Análisis de Datos
    st.header("📈 Análisis de Datos")

    st.subheader("Primeras filas del Dataset")
    st.dataframe(df.head())

    st.subheader("Distribución de Especies")
    species_count = df['species_name'].value_counts()
    fig_species = px.pie(values=species_count.values, names=species_count.index)
    st.plotly_chart(fig_species)

    st.subheader("Relación entre Características")
    fig_scatter = px.scatter(df, x='PetalLengthCm', y='PetalWidthCm',
                           color='species_name',
                           title="Longitud vs Ancho del Pétalo")
    st.plotly_chart(fig_scatter)

# Footer
st.sidebar.markdown("---")
st.sidebar.info("Proyecto Data Mining - Clasificación Iris")