# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Se2ROuqvCgSnAOwPcwcpdWYHHWAma4t
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler, LabelEncoder
import plotly.express as px
import plotly.graph_objects as go

# Configuración de la página
st.set_page_config(page_title="Clasificación Iris", page_icon="🌿", layout="wide")


@st.cache_data
def load_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['species'] = iris.target
    df['species_name'] = df['species'].map({0: 'Iris-setosa', 1: 'Iris-versicolor', 2: 'Iris-virginica'})
    return df, iris.feature_names

df, feature_names = load_data()

# Renombrar columnas para coincidir con el formato original
df = df.rename(columns={
    'sepal length (cm)': 'SepalLengthCm',
    'sepal width (cm)': 'SepalWidthCm',
    'petal length (cm)': 'PetalLengthCm',
    'petal width (cm)': 'PetalWidthCm'
})

features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
species_names = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

# Entrenar modelo
X = df[features]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Streamlit Dashboard
st.title("🌿 Clasificación de Especies de Iris")
st.write("Dashboard interactivo para predecir la especie de una flor Iris basada en sus medidas.")

# Sidebar para navegación
st.sidebar.title("Navegación")
section = st.sidebar.radio("Ir a:", ["📊 Métricas del Modelo", "🔮 Predecir Especie", "📈 Análisis Exploratorio"])

if section == "📊 Métricas del Modelo":
    st.header("📊 Métricas del Modelo (Random Forest)")

    # Métricas principales
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Exactitud", f"{accuracy_score(y_test, y_pred):.2f}")
    with col2:
        st.metric("Precisión", f"{precision_score(y_test, y_pred, average='weighted'):.2f}")
    with col3:
        st.metric("Sensibilidad", f"{recall_score(y_test, y_pred, average='weighted'):.2f}")
    with col4:
        st.metric("Puntuación F1", f"{f1_score(y_test, y_pred, average='weighted'):.2f}")

    # Matriz de confusión
    st.subheader("Matriz de Confusión")
    cm = confusion_matrix(y_test, y_pred)
    fig_cm = px.imshow(cm,
                       labels=dict(x="Predicho", y="Real", color="Cantidad"),
                       x=species_names,
                       y=species_names,
                       title="Matriz de Confusión")
    fig_cm.update_layout(width=600, height=500)
    st.plotly_chart(fig_cm)

elif section == "🔮 Predecir Especie":
    st.header("🔮 Predecir Nueva Muestra")

    # Entrada de usuario
    col1, col2 = st.columns(2)

    with col1:
        sepal_length = st.number_input("Longitud del Sépalo (cm)", min_value=0.0, max_value=10.0, value=5.8)
        sepal_width = st.number_input("Ancho del Sépalo (cm)", min_value=0.0, max_value=10.0, value=3.0)

    with col2:
        petal_length = st.number_input("Longitud del Pétalo (cm)", min_value=0.0, max_value=10.0, value=4.0)
        petal_width = st.number_input("Ancho del Pétalo (cm)", min_value=0.0, max_value=10.0, value=1.2)

    if st.button("🎯 Predecir Especie", type="primary"):
        input_data = scaler.transform([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(input_data)[0]
        prediction_proba = model.predict_proba(input_data)[0]
        species_name = species_names[prediction]

        # Mostrar resultado
        st.success(f"**Especie Predicha:** {species_name}")

        # Mostrar probabilidades
        st.subheader("Probabilidades por Especie:")
        prob_df = pd.DataFrame({
            'Especie': species_names,
            'Probabilidad': prediction_proba
        })
        fig_proba = px.bar(prob_df, x='Especie', y='Probabilidad',
                          color='Probabilidad', color_continuous_scale='Viridis',
                          title="Probabilidad de Predicción por Especie")
        st.plotly_chart(fig_proba)

else:  # Análisis Exploratorio
    st.header("📈 Análisis Exploratorio de Datos")

    # Estadísticas descriptivas
    st.subheader("Estadísticas Descriptivas")
    st.dataframe(df[features + ['species_name']].describe())

    # Distribución de especies
    st.subheader("Distribución de Especies")
    species_count = df['species_name'].value_counts()
    fig_species = px.pie(values=species_count.values,
                        names=species_count.index,
                        title="Distribución de Especies en el Dataset")
    st.plotly_chart(fig_species)

    # Pairplot simplificado
    st.subheader("Relación entre Características")
    fig_pair = px.scatter_matrix(df,
                                dimensions=features,
                                color='species_name',
                                title="Relación entre Todas las Características")
    fig_pair.update_layout(height=600)
    st.plotly_chart(fig_pair)

# Footer
st.sidebar.markdown("---")
st.sidebar.info("Proyecto de Clasificación de Especies de Iris - Data Mining")