# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Se2ROuqvCgSnAOwPcwcpdWYHHWAma4t
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler, LabelEncoder
import plotly.express as px
import plotly.graph_objects as go

# Configuración de la página
st.set_page_config(page_title="Clasificación Iris", page_icon="🌿", layout="wide")

# Cargar datos desde el CSV
@st.cache_data
def load_data():
    df = pd.read_csv('Iris.csv')
    return df

df = load_data()

# Preprocesamiento
df_clean = df.drop('Id', axis=1)  # Eliminar columna Id

# Codificar especies
le = LabelEncoder()
df_clean['species_encoded'] = le.fit_transform(df_clean['Species'])
species_names = le.classes_

# Entrenar modelo
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
X = df_clean[features]
y = df_clean['species_encoded']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Streamlit Dashboard
st.title("🌿 Clasificación de Especies de Iris")
st.write("Dashboard interactivo para predecir la especie de una flor Iris basada en sus medidas.")

# Sidebar para navegación
st.sidebar.title("Navegación")
section = st.sidebar.radio("Ir a:", [" Métricas del Modelo", "Predecir Especie", " Análisis Exploratorio"])

if section == " Métricas del Modelo":
    st.header(" Métricas del Modelo (Random Forest)")

    # Métricas principales
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Exactitud", f"{accuracy_score(y_test, y_pred):.2f}")
    with col2:
        st.metric("Precisión", f"{precision_score(y_test, y_pred, average='weighted'):.2f}")
    with col3:
        st.metric("Sensibilidad", f"{recall_score(y_test, y_pred, average='weighted'):.2f}")
    with col4:
        st.metric("Puntuación F1", f"{f1_score(y_test, y_pred, average='weighted'):.2f}")

    # Matriz de confusión
    st.subheader("Matriz de Confusión")
    cm = confusion_matrix(y_test, y_pred)
    fig_cm = px.imshow(cm,
                       labels=dict(x="Predicho", y="Real", color="Cantidad"),
                       x=species_names,
                       y=species_names,
                       title="Matriz de Confusión")
    fig_cm.update_layout(width=600, height=500)
    st.plotly_chart(fig_cm)

    # Reporte de clasificación
    st.subheader("Reporte de Clasificación")
    report = classification_report(y_test, y_pred, target_names=species_names, output_dict=True)
    report_df = pd.DataFrame(report).transpose()
    st.dataframe(report_df.style.highlight_max(axis=0, color='lightgreen'))

elif section == " Predecir Especie":
    st.header(" Predecir Nueva Muestra")

    # Entrada de usuario
    col1, col2 = st.columns(2)

    with col1:
        sepal_length = st.number_input("Longitud del Sépalo (cm)", min_value=0.0, max_value=10.0, value=5.8)
        sepal_width = st.number_input("Ancho del Sépalo (cm)", min_value=0.0, max_value=10.0, value=3.0)

    with col2:
        petal_length = st.number_input("Longitud del Pétalo (cm)", min_value=0.0, max_value=10.0, value=4.0)
        petal_width = st.number_input("Ancho del Pétalo (cm)", min_value=0.0, max_value=10.0, value=1.2)

    if st.button(" Predecir Especie", type="primary"):
        input_data = scaler.transform([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(input_data)[0]
        prediction_proba = model.predict_proba(input_data)[0]
        species_name = species_names[prediction]

        # Mostrar resultado
        st.success(f"**Especie Predicha:** {species_name}")

        # Mostrar probabilidades
        st.subheader("Probabilidades por Especie:")
        prob_df = pd.DataFrame({
            'Especie': species_names,
            'Probabilidad': prediction_proba
        })
        fig_proba = px.bar(prob_df, x='Especie', y='Probabilidad',
                          color='Probabilidad', color_continuous_scale='Viridis',
                          title="Probabilidad de Predicción por Especie")
        st.plotly_chart(fig_proba)

        # Gráfico 3D interactivo
        st.subheader("Ubicación de la Muestra en el Dataset")

        fig_3d = px.scatter_3d(df_clean,
                              x='SepalLengthCm',
                              y='SepalWidthCm',
                              z='PetalLengthCm',
                              color='Species',
                              title="Distribución 3D de Especies de Iris",
                              labels={
                                  'SepalLengthCm': 'Long Sépalo (cm)',
                                  'SepalWidthCm': 'Ancho Sépalo (cm)',
                                  'PetalLengthCm': 'Long Pétalo (cm)'
                              })

        # Añadir nueva muestra
        fig_3d.add_trace(go.Scatter3d(
            x=[sepal_length],
            y=[sepal_width],
            z=[petal_length],
            mode='markers',
            marker=dict(size=10, color='red', symbol='x', line=dict(width=2, color='darkred')),
            name='Muestra Nueva'
        ))

        st.plotly_chart(fig_3d)

else:  # Análisis Exploratorio
    st.header(" Análisis Exploratorio de Datos")

    # Estadísticas descriptivas
    st.subheader("Estadísticas Descriptivas")
    st.dataframe(df_clean[features + ['Species']].describe())

    # Distribución de especies
    st.subheader("Distribución de Especies")
    species_count = df_clean['Species'].value_counts()
    fig_species = px.pie(values=species_count.values,
                        names=species_count.index,
                        title="Distribución de Especies en el Dataset")
    st.plotly_chart(fig_species)

    # Pairplot simplificado
    st.subheader("Relación entre Características (Pair Plot)")
    fig_pair = px.scatter_matrix(df_clean,
                                dimensions=features,
                                color='Species',
                                title="Pair Plot - Relación entre Todas las Características")
    fig_pair.update_layout(height=800)
    st.plotly_chart(fig_pair)

    # Histogramas por especie
    st.subheader("Distribución de Características por Especie")
    feature_select = st.selectbox("Selecciona una característica:", features)

    fig_hist = px.histogram(df_clean,
                           x=feature_select,
                           color='Species',
                           barmode='overlay',
                           title=f'Distribución de {feature_select} por Especie',
                           marginal='box')
    st.plotly_chart(fig_hist)

    # Heatmap de correlación
    st.subheader("Mapa de Calor de Correlaciones")
    numeric_df = df_clean[features + ['species_encoded']]
    corr_matrix = numeric_df.corr()

    fig_heatmap = px.imshow(corr_matrix,
                           labels=dict(color="Correlación"),
                           x=corr_matrix.columns,
                           y=corr_matrix.columns,
                           title="Matriz de Correlación",
                           color_continuous_scale='RdBu_r',
                           aspect="auto")
    fig_heatmap.update_layout(width=600, height=500)
    st.plotly_chart(fig_heatmap)

# Footer
st.sidebar.markdown("---")
st.sidebar.info("Proyecto de Clasificación de Especies de Iris - Data Mining")